export const USER_ACTION_TYPES = {
  CHECK_USER_SESSION: "user/CHECK_USER_SESSION",
  EMAIL_SIGN_IN_START: "user/EMAIL_SIGN_IN_START",
  GOOGLE_SIGN_IN_START: "user/GOOGLE_SIGN_IN_START",
  SET_CURRENT_USER: "user/SET_CURRENT_USER",
  SIGN_IN_FAILED: "user/SIGN_IN_FAILED",
  SIGN_IN_SUCCESS: "user/SIGN_IN_SUCCESS"
}
